import type { AppLocale } from '@/i18n/locales';
import type { SignaturePageCopy } from './signaturePages';

export const ACNE_ROOT_COPY: Record<AppLocale, SignaturePageCopy> = {
    ko: {
        heroTitle: '여드름 뿌리 치료',
        heroSub: '반복되는 여드름의 원인부터 피부\u00A0환경까지 개선하는 근본 치료', // \u00A0 = 모바일에서 붙여 둘 띄어쓰기 (signaturePages.ts 머리말)
        name: '여드름 뿌리 치료',
        intro: {
            quote: '여드름이 반복되는 피부는 올라온 염증을 가라앉히는 것과 함께,\n여드름이 계속 생기는 피부 환경 자체를 개선하는 근본적 접근이 필요합니다.',
            causesTitle: '여드름이 계속 생기는 원인',
            causes: [
                '피지의 과도한 분비 혹은 배출의 정체',
                '그로 인한 좁쌀여드름 형성',
                '균이 좋아하는 기름진 환경에서 증식하며 염증 발생',
            ],
            note: '그렇다면 치료 역시 위의 3가지를 개선하는 방향으로 가야 합니다.',
        },
        storySub: '염증을 가라앉히고,\n여드름이 반복되는 뿌리까지 다룹니다',
        storyBody: [
            '과도한 피지분비를 억제하고, 염증의 씨앗인 좁쌀여드름을 미리미리 제거해 주며,\n이미 생긴 염증은 가라앉히는 치료를 해 주면 됩니다.',
            '여기에 진피재생 치료까지 겸해 여드름 자국들을 정상 피부로 되돌리는 것.\n그리고 장기적으로는 여드름이 잘 나지 않는 피부 컨디션을 조성하는 것.\n\n리베리 시그니처 여드름치료 프로그램이 목표하는 지향점입니다.',
        ],
        treatmentCards: [
            '피지선 파괴를 통해 피지 분비\n장기적으로 줄여주는\n**롱펄스 골드PTT**',
            '모공이 막히는 환경을\n정돈하는 **부드러운 필링**',
            '염증으로 진행할 수 있는\n씨앗을 제거하는 **압출**',
            '진피재생을 통해 여드름\n흔적을 복원하는\n**포텐자·엑소좀·피코프락셀**',
        ],
        whyTitle: '리베리의 여드름 뿌리 치료는 다릅니다',
        why: [
            '완치를 목표로, 여드름이 반복되는 원인에 접근하는 치료',
            '제네시스와 롱펄스 30ms를 병행하는 골드 PTT, 장기적인 피지 조절',
            '유분은 걷어내되 자극적이지 않은 필링',
            '압출 시간제가 아닌, 피부만을 고려한 얼굴 전체 압출',
            '포텐자·피코프락셀 등 재생 치료를 병행한 여드름 자국·흉터 개선',
            '여드름의 유형과 피부 상태, 회복 단계에 맞춘 개인별 치료 설계',
        ],
        recommend: [
            '청소년기부터 성인이 된 지금까지 여드름으로 오랫동안 고생하신 분',
            '여러 가지 여드름 치료를 받아봤지만 계속 재발하는 분',
            '여드름이 많아 어디서부터 치료해야 할지 막막한 분',
            '생리주기나 수면·스트레스 등 생활 변화에 따라 여드름이 반복되는 분',
            '과도한 피지와 좁쌀·염증성 여드름으로 고민인 분',
            '현재의 여드름과 함께 남아 있는 자국·흉터도 개선하고 싶은 분',
        ],
        closingLead: '여드름은 겉으로 드러난 염증보다',
        closingStatement: '**반복되는 뿌리부터** 치료해야 합니다.',
    },
    en: {
        heroTitle: 'Root-Cause Acne Treatment',
        heroSub: 'Addressing the causes of recurring acne and the skin environment behind it',
        name: 'Root-Cause Acne Treatment',
        intro: {
            quote: 'Recurring acne calls for more than calming existing inflammation.\nIt also requires addressing the underlying skin conditions that allow breakouts to return.',
            causesTitle: 'Why acne keeps coming back',
            causes: [
                'Excess sebum production or blocked sebum drainage',
                'The resulting formation of closed comedones',
                'Bacterial growth in an oily environment, leading to inflammation',
            ],
            note: 'Treatment should therefore address all three of these factors.',
        },
        storySub: 'Calming inflammation\nand addressing why acne keeps returning',
        storyBody: [
            'Treatment involves controlling excess sebum, removing closed comedones before they become inflamed, and calming inflammation that has already developed.',
            'Dermal regeneration treatments also help acne-marked skin recover. Over the longer term, the aim is to create a skin environment less prone to breakouts.\n\nThis is the goal of the RE:BERRY signature acne treatment program.',
        ],
        treatmentCards: [
            '**Long-pulse Gold PTT**\ntargets sebaceous glands\nto reduce sebum production over time',
            '**Gentle peeling**\nto improve conditions\nthat lead to clogged pores',
            '**Comedone extraction**\nto remove blockages\nthat can develop into inflammation',
            '**Potenza · Exosomes · Pico fractional laser**\nto support dermal regeneration\nand improve acne marks',
        ],
        whyTitle: 'What makes RE:BERRY Root-Cause Acne Treatment different',
        why: [
            'Treatment aimed at lasting resolution by addressing why acne recurs',
            'Gold PTT combining Genesis and 30 ms long-pulse treatment for long-term sebum control',
            'Gentle peeling that removes excess oil without harsh irritation',
            'Full-face extraction based on skin needs, rather than a fixed time limit',
            'Regenerative treatments such as Potenza and pico fractional laser for acne marks and scars',
            'Individual treatment plans based on acne type, skin condition and stage of recovery',
        ],
        recommend: [
            'You have struggled with acne from adolescence into adulthood',
            'Acne keeps returning despite trying different treatments',
            'You have extensive acne and are unsure where to start',
            'Breakouts recur with changes in your menstrual cycle, sleep or stress',
            'You are concerned about excess sebum, closed comedones or inflammatory acne',
            'You want to improve existing acne as well as lingering marks and scars',
        ],
        closingLead: 'Acne care goes beyond visible inflammation.',
        closingStatement: 'Treatment must address **the causes of recurring breakouts**.',
    },
    ja: {
        heroTitle: 'ニキビの根本治療',
        heroSub: '繰り返すニキビの原因から肌環境まで整える根本治療',
        name: 'ニキビの根本治療',
        intro: {
            quote: 'ニキビを繰り返す肌には、今ある炎症を鎮めることに加え、\nニキビができ続ける肌環境そのものを改善する根本的なアプローチが必要です。',
            causesTitle: 'ニキビが繰り返しできる原因',
            causes: [
                '皮脂の過剰分泌、または排出の滞り',
                'それに伴う白ニキビ（閉鎖面皰）の形成',
                '皮脂の多い環境で菌が増殖し、炎症が発生',
            ],
            note: 'そのため、治療もこの3つを改善する方向で進める必要があります。',
        },
        storySub: '炎症を鎮め、\nニキビを繰り返す根本原因までケアします',
        storyBody: [
            '過剰な皮脂分泌を抑え、炎症のもとになる白ニキビを早めに取り除き、すでに生じた炎症を鎮める治療を行います。',
            'さらに真皮の再生を促す治療を組み合わせ、ニキビ跡の残る肌を健やかな状態へ導くこと。そして長期的にニキビができにくい肌環境を整えること。\n\nそれがRE:BERRYのシグネチャーニキビ治療プログラムが目指す方向です。',
        ],
        treatmentCards: [
            '皮脂腺に働きかけ、\n皮脂分泌を長期的に抑える\n**ロングパルス・ゴールドPTT**',
            '毛穴が詰まりやすい環境を\n整える\n**低刺激のピーリング**',
            '炎症へ進む可能性のある\nニキビのもとを取り除く\n**面皰圧出**',
            '真皮の再生を促し、\nニキビ跡をケアする\n**ポテンツァ・エクソソーム・ピコフラクショナル**',
        ],
        whyTitle: 'RE:BERRYのニキビ根本治療が選ばれる理由',
        why: [
            '治癒を目指し、ニキビを繰り返す原因にアプローチする治療',
            'ジェネシスと30msのロングパルスを併用するゴールドPTTで、長期的な皮脂コントロール',
            '余分な皮脂を取り除きながら、刺激を抑えたピーリング',
            '時間制ではなく、肌の状態を優先した顔全体の面皰圧出',
            'ポテンツァやピコフラクショナルなどの再生治療を組み合わせ、ニキビ跡や瘢痕を改善',
            'ニキビの種類、肌の状態、回復段階に合わせた個別の治療計画',
        ],
        recommend: [
            '思春期から大人になった今まで、長くニキビに悩んでいる方',
            'さまざまなニキビ治療を受けても再発を繰り返す方',
            'ニキビが多く、何から治療を始めればよいか分からない方',
            '月経周期や睡眠・ストレスなどの変化に伴いニキビが繰り返しできる方',
            '過剰な皮脂や白ニキビ・炎症性ニキビに悩んでいる方',
            '今あるニキビとともに、残ったニキビ跡や瘢痕も改善したい方',
        ],
        closingLead: 'ニキビは目に見える炎症だけでなく、',
        closingStatement: '**繰り返す根本原因から**治療することが大切です。',
    },
    zh: {
        heroTitle: '痤疮根源治疗',
        heroSub: '从反复长痘的原因到皮肤环境，进行根源性改善',
        name: '痤疮根源治疗',
        intro: {
            quote: '对于反复长痘的皮肤，除了缓解已经出现的炎症，\n还需要从根源入手，改善导致痤疮不断发生的皮肤环境。',
            causesTitle: '痤疮反复发生的原因',
            causes: [
                '皮脂分泌过多，或皮脂排出受阻',
                '由此形成闭口粉刺',
                '细菌在油脂丰富的环境中繁殖，引发炎症',
            ],
            note: '因此，治疗也应围绕改善以上三个方面展开。',
        },
        storySub: '缓解炎症，\n同时处理痤疮反复发生的根源',
        storyBody: [
            '抑制过多的皮脂分泌，提前清除可能引发炎症的闭口粉刺，并对已经发生的炎症进行治疗。',
            '同时结合真皮再生治疗，帮助留有痘印的皮肤恢复健康状态。从长期来看，目标是营造不易长痘的皮肤环境。\n\n这正是RE:BERRY招牌痤疮治疗方案所追求的方向。',
        ],
        treatmentCards: [
            '作用于皮脂腺，\n长期减少皮脂分泌的\n**长脉冲黄金PTT**',
            '改善毛孔易堵塞环境的\n**温和焕肤**',
            '清除可能发展为炎症的\n粉刺堵塞的\n**粉刺清除治疗**',
            '促进真皮再生、改善痘印的\n**Potenza·外泌体·皮秒点阵**',
        ],
        whyTitle: 'RE:BERRY痤疮根源治疗的不同之处',
        why: [
            '以治愈为目标，针对痤疮反复发生的原因进行治疗',
            '结合Genesis与30毫秒长脉冲的黄金PTT，进行长期皮脂调控',
            '去除多余油脂，同时减少刺激的温和焕肤',
            '以皮肤需求为依据，进行不限固定时长的全脸粉刺清除',
            '联合Potenza、皮秒点阵等再生治疗，改善痘印与痘疤',
            '根据痤疮类型、皮肤状态及恢复阶段制定个人治疗方案',
        ],
        recommend: [
            '从青春期到成年一直受痤疮困扰的人',
            '尝试过多种痤疮治疗，但仍不断复发的人',
            '痤疮较多，不知道应从哪里开始治疗的人',
            '随月经周期、睡眠或压力等生活变化而反复长痘的人',
            '受皮脂过多、闭口粉刺或炎症性痤疮困扰的人',
            '希望同时改善现有痤疮以及残留痘印、痘疤的人',
        ],
        closingLead: '痤疮治疗不应只关注表面炎症，',
        closingStatement: '更应从**反复发生的根源**入手。',
    },
};
