// #ISSUE: 장비(equipment)+제품(products) 단일 진실 공급원(SSOT) 통합 — 카드와 상세 페이지가 이 파일 하나만 봄
// #MEMO: 상세 내용 채우는 곳: 각 항목의 subTitle / introDescription / principles (빈 값이면 상세 페이지가 기본 구성으로 렌더링 함)

export interface SolutionPrinciple {
    title: string;
    content: string;
}

export interface SolutionItem {
    slug: string;
    category: string[];
    name: string;
    engName: string;
    desc: [string, string];
    point: string;
    image: string;
    type: 'device' | 'product';
    detailImage: string;
    subTitle: string;
    introDescription: string;
    principles: SolutionPrinciple[];
}

const eq = (n: number) => `/images/items/eq-${String(n).padStart(2, '0')}.jpg`;
const pr = (n: number) => `/images/items/pr-${String(n).padStart(2, '0')}.jpg`;

export const solutions: SolutionItem[] = [
    // --- Devices ---
    {
        slug: 'potenza',
        category: ['여드름', '주사/홍조'],
        name: '포텐자',
        engName: 'Potenza',
        desc: ['피부 타입별 정밀 맞춤 시술', '손상 최소화 및 피부 결 재생'],
        point: '모공, 흉터, 탄력',
        image: eq(1),
        type: 'device',
        detailImage: eq(1),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'excelv',
        category: ['색소', '주사/홍조'],
        name: '엑셀V',
        engName: 'Excel V',
        desc: ['혈관 병변 및 붉은기 개선', '피부 고민별 맞춤 시술 가능'],
        point: '홍조, 혈관, 민감성',
        image: eq(2),
        type: 'device',
        detailImage: eq(2),
        subTitle: '세 가지 모드로 다양한 피부 고민을\n해결하는 복합 레이저',
        introDescription:
            '안면홍조, 모세혈관 확장증 등 혈관 문제부터\n기미, 잡티, 탄력까지 한 번에 개선하고 싶을 때,\n복합적인 피부 고민을 해결하는 엑셀V 레이저입니다.',
        principles: [
            {
                title: '엑셀V 레이저란?',
                content:
                    '엑셀V는 532nm KTP, 1064nm Nd:YAG, 그리고 제네시스 마이크로세컨드 모드 등 3가지 파장과 모드를 활용하는 멀티 솔루션 장비입니다.\n단일 파장으로는 치료가 까다로웠던 복합적인 피부 문제를 각 깊이와 병변에 맞춰 정밀하게 타겟팅합니다.',
            },
            {
                title: '혈관 및 홍조 치료에 특화된 이유',
                content:
                    '피부 표피층의 붉은기부터 깊은 진피층의 푸른 혈관까지 각기 다른 혈관성 병변에 최적화된 파장을 선택할 수 있습니다.\n또한 사파이어 쿨링 시스템을 통해 시술 시 피부 표면을 보호하고 통증을 줄여, 예민하고 붉은 피부도 편안하게 시술받을 수 있습니다.',
            },
            {
                title: '리베리의원의 엑셀V 시술 원칙',
                content:
                    '홍조와 색소 병변은 단순한 표면 치료가 아닌 진피층의 환경 개선이 동반되어야 합니다.\n리베리의원은 3D 입체 분석을 통해 병변의 깊이와 넓이를 정확히 진단하고, 증상에 맞춘 파장과 에너지 조절을 통해 피부 장벽의 손상 없이 맑고 건강한 피부톤을 되찾아 드립니다.',
            },
        ],
    },
    {
        slug: 'synerjet',
        category: [],
        name: '시너젯',
        engName: 'Synerjet',
        desc: ['공기압 이용 유착 흉터 복원', '패인 부위 콜라겐 생성 및 리프팅'],
        point: '흉터, 유착, 볼륨 시술',
        image: eq(3),
        type: 'device',
        detailImage: eq(3),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'revinas',
        category: [],
        name: '레비나스',
        engName: 'Revinas',
        desc: ['PLA 성분으로 콜라겐 생성을 유도', '자연스러운 볼륨과 피부 탄력 개선'],
        point: '볼륨, 탄력, 콜라겐',
        image: eq(4),
        type: 'device',
        detailImage: eq(4),
        subTitle: '옆볼 유착부터\n피부결·윤곽·잔주름까지',
        introDescription:
            '레비나스는 체외 충격파로 피부와 피하조직,\n근막층에 물리적 자극을 전달하는 시술입니다.\n열에너지 리프팅과 달리 유착된 조직을 풀어주며\n미세순환과 조직 재생을 유도합니다.',
        principles: [
            {
                title: '꺼져 보이는 옆볼 유착 개선',
                content:
                    '나이가 들거나 반복적인 시술·수술을 받은 뒤에는 옆볼의 피부와 피하조직이 유착되면서 실제 지방량보다 더 깊게 꺼져 보일 수 있습니다.\n레비나스는 이러한 섬유화와 유착을 완화해 조직이 자연스럽게 움직일 수 있도록 돕습니다. 무언가를 채우는 시술이 아니기 때문에 과도하게 볼륨이 생길 우려가 적고, 옆볼·팔자·심부볼의 연결이 보다 부드럽게 정리됩니다.',
            },
            {
                title: '심부볼과 이중턱 윤곽 개선',
                content:
                    '충격파는 조직의 미세순환을 촉진하고 부종을 완화하는 데 도움을 줍니다. 이를 통해 무겁게 처져 보이던 심부볼과 이중턱이 정리되면서 턱선이 조금 더 선명하고 가벼워 보이는 것을 목표로 합니다.\n보톡스처럼 근육을 강하게 억제하지 않아 표정이 어색해질 부담이 적고, 이마·미간·자갈턱 등의 잔주름을 부드럽게 만드는 데도 도움을 줄 수 있습니다.',
            },
        ],
    },
    {
        slug: 'shrink',
        category: ['리프팅'],
        name: '슈링크 유니버스',
        engName: 'Shrink Universe',
        desc: ['초음파 리프팅으로 피부 탄력 개선', '처진 윤곽을 정리하고 리프팅 효과'],
        point: '리프팅, 탄력, 윤곽',
        image: eq(5),
        type: 'device',
        detailImage: eq(5),
        subTitle: '깊은 층의 처짐을\n초음파로 당겨 올리는 리프팅',
        introDescription:
            '슈링크는 고강도 집속초음파를 피부 깊은 층에\n전달해 열응고점을 만드는 리프팅 시술입니다.\n늘어진 조직을 수축시키고 콜라겐 재생을 유도해\n심부볼·턱선·이중턱의 처짐을 개선합니다.',
        principles: [
            {
                title: '얼굴에 맞춘 깊이별 시술',
                content:
                    '여러 깊이의 카트리지를 활용해 피부 두께와 처짐 정도에 맞춰 치료할 수 있습니다. 깊은 층은 윤곽 리프팅을, 얕은 층은 피부 탄력 개선을 목적으로 사용합니다.',
            },
            {
                title: '볼패임을 줄이는 맞춤 디자인',
                content:
                    '앞볼과 옆볼처럼 지방이 부족한 부위에 에너지를 과도하게 조사하면 얼굴이 더 꺼져 보일 수 있습니다. 꺼진 부위는 피하고 팔자·심부볼·턱선처럼 실제로 처진 부위를 집중적으로 시술해야 자연스러운 결과를 얻을 수 있습니다.',
            },
        ],
    },
    {
        slug: 'inmode',
        category: [],
        name: '인모드',
        engName: 'Inmode',
        desc: ['고주파 에너지로 탄력 개선 및 리프팅', '불필요한 지방 감소와 윤곽 정리'],
        point: '리프팅, 탄력, 윤곽',
        image: eq(6),
        type: 'device',
        detailImage: eq(6),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'titanium',
        category: [],
        name: '티타늄',
        engName: 'Titanium',
        desc: ['3가지 파장을 활용한 복합 리프팅', '피부 탄력 개선 및 얼굴 윤곽 정리'],
        point: '리프팅, 탄력, 윤곽',
        image: eq(7),
        type: 'device',
        detailImage: eq(7),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'lipot',
        category: ['색소'],
        name: '리팟',
        engName: 'Lipot',
        desc: ['피부 고민별 맞춤 시술 가능', '피부결 개선 및 피부 재생 케어'],
        point: '재생, 피결, 탄력',
        image: eq(8),
        type: 'device',
        detailImage: eq(8),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'spectra',
        category: ['색소'],
        name: '헐리우드 스펙트라',
        engName: 'Hollywood Spectra',
        desc: ['기미·잡티·난치성 색소 개선', '모공·피부톤 개선 및 탄력 케어'],
        point: '색소, 톤, 모공',
        image: eq(9),
        type: 'device',
        detailImage: eq(9),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'pico',
        category: ['색소'],
        name: '피코 플러스',
        engName: 'Pico Plus',
        desc: ['기미·잡티·난치성 색소 개선', '모공·문신 제거 및 피부결 개선'],
        point: '색소, 문신, 피부결',
        image: eq(10),
        type: 'device',
        detailImage: eq(10),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'clarity',
        category: [],
        name: '클라리티',
        engName: 'Clarity',
        desc: ['기미·잡티·난치성 색소 개선', '모공·문신 제거 및 피부결 개선'],
        point: '색소, 문신, 피부결',
        image: eq(11),
        type: 'device',
        detailImage: eq(11),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'pico2',
        category: [],
        name: '피코프락셀',
        engName: 'Pico Fraxel',
        desc: ['피코 레이저 기반 저자극 흉터 케어', '미세 빔 활용 모공 타이트닝'],
        point: '모공, 흉터, 재생 시술',
        image: eq(12),
        type: 'device',
        detailImage: eq(12),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'ulthera',
        category: ['리프팅'],
        name: '울쎄라',
        engName: 'Ulthera',
        desc: ['고강도 초음파 리프팅', '처진 피부 탄력 개선 및 윤곽 리프팅'],
        point: '탄력, 리프팅, 이중턱',
        image: eq(13),
        type: 'device',
        detailImage: eq(13),
        subTitle: '초음파 에너지로 피부 깊은 층을\n당겨주는 원조 리프팅 레이저',
        introDescription:
            '나이가 들며 얼굴선이 무너지고\n탄력이 떨어지기 시작할 때,\n피부과 리프팅 시술 중 가장 먼저 떠올리게 되는\n리프팅 레이저가 바로 울쎄라입니다.',
        principles: [
            {
                title: '통증과 볼패임 걱정을 줄인 맞춤 울쎄라피프라임',
                content:
                    '울쎄라는 초음파 화면으로 피부 속 구조를 확인하며 원하는 깊이에 에너지를 전달하는 리프팅 시술입니다. 열응고점을 통해 콜라겐 재생과 조직 리모델링을 유도하며, 특히 심부볼·팔자·턱선·이중턱 개선에 효과적으로 활용됩니다.\n효과는 시술 직후보다 서서히 나타납니다. 새로운 콜라겐이 성숙하는 데 약 3개월이 필요하므로 보통 피크 효과는 12주 전후입니다.',
            },
            {
                title: '볼패임은 디자인으로 예방, 필요한 부위에만 시술',
                content:
                    '앞볼과 옆볼처럼 원래 꺼져 있거나 지방이 부족한 부위에 에너지가 과도하게 들어가면 얼굴이 수척해 보일 수 있습니다. 따라서 이러한 부위는 시술을 피하고, 실제로 처짐이 두드러지는 심부볼·팔자·턱선·이중턱을 중심으로 시술합니다.\n얼굴의 지방/유지인대 분포와 처짐의 방향을 먼저 분석한 뒤 필요한 부위에만 깊이와 방향을 달리해 조사하면, 볼패임의 위험 없이 자연스러운 리프팅 효과를 얻을 수 있습니다.',
            },
            {
                title: '무조건 수면마취가 답일까? — 통증이 무섭다면',
                content:
                    '울쎄라 시술 시 통증이 심한 팔자와 턱선 부위는 감각신경을 선택적으로 주사로 마취하고 장시간 크림 마취를 함께 사용하면 불편감을 크게 줄일 수 있습니다.\n논문 데이터상으로 신경마취 후 통증점수가 7.5점에서 2.9점으로 낮아졌으며, 울쎄라에서 울쎄라피 프라임으로 업그레이드되면서 기존 울쎄라보다 시술 중 통증과 시술 후 부종·발적이 거의 절반 가까이 줄었다는 설문논문 결과도 존재합니다.\n울쎄라는 단순히 많은 샷을 조사하는 시술이 아닙니다. 얼굴형과 지방 분포를 고려한 정교한 디자인, 정확한 깊이 설정, 적절한 통증 조절이 함께 이루어져야 편안하고 자연스러운 결과를 기대할 수 있습니다.',
            },
        ],
    },
    {
        slug: 'onda',
        category: ['리프팅'],
        name: '온다',
        engName: 'Onda',
        desc: ['마이크로웨이브 지방 감소', '이중턱·볼살 개선 및 탄력 강화'],
        point: '지방, 윤곽, 탄력',
        image: eq(14),
        type: 'device',
        detailImage: eq(14),
        subTitle: '열에너지를 전달해서\n지방세포를 축소·사멸하는 리프팅',
        introDescription:
            '얼굴을 처져 보이게 하는 가장 큰 원인은\n피부의 탄력 저하가 아니라 지방의 분포 변화입니다.\n온다는 마이크로웨이브로 지방층을 줄여\n이중턱·팔자윗살·심부볼·턱선을 개선합니다.',
        principles: [
            {
                title: '유효기간이 짧은 리프팅이다?',
                content:
                    '온다는 유지기간이 아쉽다는 이야기가 종종 나오는 리프팅입니다. 하지만 1회 시술이라도 지방이 충분한 부위에 에너지를 효과적으로 전달하여 지방세포에 충분한 변화를 유도한다면, 유지기간 역시 더 길게 기대할 수 있습니다.\n저희는 온다의 핵심 원리인 보강·상쇄간섭을 최대한 활용하기 위해 한 자세에서만 시술하지 않습니다. 시술 부위와 얼굴의 곡선을 고려하여 환자의 자세를 바꿔가며 여러 방향에서 에너지를 전달함으로써, 지방이 많은 부위에 보다 효과적으로 에너지를 집중시키고자 합니다.',
            },
            {
                title: '콜라겐 생성을 통한 피부 겉면 탄력까지?',
                content:
                    '온다는 피부 표면으로부터 3mm, 7mm까지 침투하는 두 가지 핸드피스를 가집니다. 7mm는 앞서 설명한 지방세포에 작용하여 장기적인 윤곽 개선을 목표로 하고, 3mm는 피부 탄력을 개선하여 리프팅 효과를 높여줍니다.\n저희는 3mm 팁을 사용할 때 피부 장력선을 고려하여 콜라겐이 위쪽 방향으로 효과적으로 수축될 수 있도록 시술합니다. 이를 통해 장기적인 윤곽 개선뿐 아니라, 피부가 위로 달라붙는 즉각적인 리프팅 효과까지 함께 기대할 수 있습니다.',
            },
        ],
    },
    {
        slug: 'vro',
        category: ['리프팅'],
        name: '브이로',
        engName: 'V-RO',
        desc: ['피부층별 맞춤 리프팅 가능', '탄력 개선 및 얼굴 윤곽 정리'],
        point: '리프팅, 탄력,윤곽',
        image: eq(15),
        type: 'device',
        detailImage: eq(15),
        subTitle: '초음파와 고주파를 동시에\n윤곽과 피부결까지 개선하는 리프팅',
        introDescription:
            '브이로는 초음파 리프팅과 양극성 고주파를\n동시에 전달하는 복합 리프팅 장비입니다.\n깊은 층의 처짐부터 피부 표면의 탄력과 잔주름까지\n한 번의 시술로 함께 개선할 수 있습니다.',
        principles: [
            {
                title: '초음파로 처진 구조를 당겨 올리다',
                content:
                    '초음파 에너지는 피부 깊은 곳의 근막층까지 열응고점을 만들어 처진 조직을 수축시키고 콜라겐 재생을 유도합니다. 브이로는 기존 슈링크보다 높은 기본 출력으로 설정되어 있어 강한 윤곽 리프팅을 기대할 수 있습니다.',
            },
            {
                title: '고주파로 피부 표면을 탄탄하게',
                content:
                    '양극성 고주파는 비교적 얕은 피부층에 열을 넓게 전달해 콜라겐 합성을 촉진하고 피부 탄력과 잔주름을 개선합니다. 초음파가 얼굴의 처진 구조를 당겨 올리는 역할을 한다면, 고주파는 피부 표면을 탄탄하고 매끄럽게 정돈하는 역할을 합니다.',
            },
        ],
    },
    {
        slug: 'clarity2',
        category: [],
        name: '클라리티2',
        engName: 'Clarity 2',
        desc: ['모근 깊이별 맞춤형 레이저 제모', '지능형 냉각 시스템으로 통증 최소화'],
        point: '모발, 통증, 맞춤 제모',
        image: eq(16),
        type: 'device',
        detailImage: eq(16),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'aqua',
        category: [],
        name: '아쿠아필',
        engName: 'Aqua Peel',
        desc: ['모공 속 피지 및 블랙헤드 제거', '수분 공급 및 각질 개선 효과'],
        point: '피지, 모공, 수분',
        image: eq(17),
        type: 'device',
        detailImage: eq(17),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'cryocell',
        category: [],
        name: '크라이오셀',
        engName: 'Cryocell',
        desc: ['냉동 이온 침투로 피부 진정 및 쿨링', '시술 후 자극된 피부 장벽 재생'],
        point: '진정, 붉은기, 쿨링',
        image: eq(18),
        type: 'device',
        detailImage: eq(18),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'ionzyme',
        category: [],
        name: '이온자임·이온토 관리',
        engName: 'Ionzyme',
        desc: ['고농도 비타민 침투로 강력한 미백 효과', '멜라닌 형성 억제 및 잡티 개선'],
        point: '미백, 비타민, 잡티',
        image: eq(19),
        type: 'device',
        detailImage: eq(19),
        subTitle: '',
        introDescription: '',
        principles: [],
    },

    // --- Products ---
    {
        slug: 'lituo',
        category: [],
        name: '리투오',
        engName: 'Lituo',
        desc: ['피부 턴오버 주기 정상화 및 재생', '거친 피부 결 및 안색 개선'],
        point: '피부결, 안색, 재생시술',
        image: pr(1),
        type: 'product',
        detailImage: pr(1),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'deuce',
        category: [],
        name: '듀스',
        engName: 'Deuce',
        desc: ['자연스러운 리프팅과 탄력 개선', '탄력 개선과 또렷한 얼굴 윤곽 완성'],
        point: '리프팅, 탄력, 윤곽',
        image: pr(2),
        type: 'product',
        detailImage: pr(2),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'restylane',
        category: [],
        name: '레스틸렌',
        engName: 'Restylane',
        desc: ['깊은 주름 개선 및 얼굴 볼륨업', '정교한 라인 교정'],
        point: '볼륨, 라인',
        image: pr(3),
        type: 'product',
        detailImage: pr(3),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'belotero-soft',
        category: [],
        name: '벨로테로 소프트',
        engName: 'Belotero Soft',
        desc: ['자연스러운 표정 연출', '섬세한 주름 개선'],
        point: '밀착력, 자연스러움',
        image: pr(4),
        type: 'product',
        detailImage: pr(4),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'renefill',
        category: [],
        name: '르네필',
        engName: 'Renefill',
        desc: ['얼굴 윤곽 교정', '꺼진 부위 볼륨 충전'],
        point: '볼륨, 윤곽, 점탄성',
        image: pr(5),
        type: 'product',
        detailImage: pr(5),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'lenafill',
        category: [],
        name: '레나필',
        engName: 'Lenafill',
        desc: ['얼굴 입체감 형성', '전반적인 피부 윤곽 개선'],
        point: '볼륨, 안전성, 입체감',
        image: pr(6),
        type: 'product',
        detailImage: pr(6),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'artier',
        category: [],
        name: '아띠에르',
        engName: 'Artier',
        desc: ['이목구비 볼륨 강화', '또렷한 윤곽 라인 완성'],
        point: '몰딩력, 유지력, 윤곽 개선',
        image: pr(7),
        type: 'product',
        detailImage: pr(7),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'dca',
        category: [],
        name: 'DCA주사',
        engName: 'DCA Injection',
        desc: ['지방 세포 파괴, 이중턱 개선', '이중턱 개선'],
        point: '지방 파괴, 턱선 교정',
        image: pr(8),
        type: 'product',
        detailImage: pr(8),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'wegovy',
        category: [],
        name: '위고비',
        engName: 'Wegovy',
        desc: ['식욕 억제 도움', '체지방 개선'],
        point: '식단 관리, 체중 조절',
        image: pr(9),
        type: 'product',
        detailImage: pr(9),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'rejuran-healer',
        category: [],
        name: '리쥬란 힐러',
        engName: 'Rejuran Healer',
        desc: ['PN 성분 기반 피부 세포 재생 촉진', '유수분 밸런스 회복 및 탄력 개선'],
        point: '재생, 탄력, 피부 케어',
        image: pr(10),
        type: 'product',
        detailImage: pr(10),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'lillide',
        category: [],
        name: '릴리이드',
        engName: 'Lillide',
        desc: ['피부 장벽 강화', '건조한 피부 속 깊은 수분감 보충'],
        point: '장벽, 수분, 재생 시술',
        image: pr(11),
        type: 'product',
        detailImage: pr(11),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'newarti',
        category: [],
        name: '뉴아티',
        engName: 'Newarti',
        desc: ['고농축 아미노산 및 히알루론산 주입', '피부 광채 촉진 및 미세 주름 개선'],
        point: '광채, 보습, 탄력 케어',
        image: pr(12),
        type: 'product',
        detailImage: pr(12),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'gold-ptt',
        category: ['여드름', '주사/홍조'],
        name: 'Gold PTT',
        engName: 'Gold PTT',
        desc: ['피부 고민별 1:1 맞춤형 솔루션', '근본적인 피부 환경 개선 및 화사한 톤'],
        point: '색조, 홍조, 모공',
        image: pr(13),
        type: 'product',
        detailImage: pr(13),
        subTitle: '특수 설계된 골드 입자로\n여드름의 근본 원인을 파괴하다',
        introDescription:
            '반복되는 여드름과 늘어나는 피지 분비가 고민일 때,\n골드 마이크로 입자와 레이저를 결합하여\n피지선과 여드름 균을 선택적으로 파괴하는 타겟 치료입니다.',
        principles: [
            {
                title: 'Gold PTT란?',
                content:
                    '특수 코팅된 미세 골드 입자를 피부 깊숙한 피지선과 여드름 균에 침투시킨 후, 특정 파장의 레이저를 조사하는 시술입니다.\n레이저 빛을 흡수한 골드 입자가 국소적인 열을 발생시켜 여드름의 근본 원인이 되는 피지선을 파괴하고 균을 사멸시킵니다.',
            },
            {
                title: '재발 잦은 여드름에 효과적인 이유',
                content:
                    '표면적인 각질 정리나 일시적인 염증 완화가 아닌, 여드름을 유발하는 피지선 자체의 활성도를 낮추어 재발률을 현저히 떨어뜨립니다.\n주변 정상 피부 조직의 손상을 줄이면서 타겟팅된 부위에만 작용하므로, 시술 후 건조함이나 홍조 등의 부작용 발생을 줄일 수 있습니다.',
            },
            {
                title: '리베리의원의 Gold PTT 시술 원칙',
                content:
                    '단순히 용액을 도포하고 레이저를 조사하는 것에 그치지 않습니다.\n리베리의원은 골드 입자가 모공 속으로 충분히 흡수될 수 있도록 사전 스케일링과 초음파 침투 관리를 병행합니다. 개인의 피지 분비량과 피부 민감도에 맞춰 레이저의 강도와 횟수를 조절하는 맞춤형 치료를 지향합니다.',
            },
        ],
    },
    {
        slug: 'juvelook-volume',
        category: ['리프팅'],
        name: '쥬베룩 볼륨',
        engName: 'Juvelook Volume',
        desc: ['콜라겐 생성으로 자연스러운 볼륨 개선', '꺼진 부위 및 피부 탄력 개선'],
        point: '볼륨, 탄력, 콜라겐',
        image: pr(14),
        type: 'product',
        detailImage: pr(14),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'exosome',
        category: ['여드름'],
        name: '엑소좀',
        engName: 'Exosome',
        desc: ['피부 타입별 정밀 맞춤 시술', '손상 최소화 및 피부 결 재생'],
        point: '모공, 흉터, 탄력',
        image: pr(15),
        type: 'product',
        detailImage: pr(15),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'juvelook',
        category: [],
        name: '쥬베룩',
        engName: 'Juvelook',
        desc: ['콜라겐 재생으로 볼륨형성', '패인 흉터, 잔주름 및 모공 개선'],
        point: '볼륨, 탄력, 흉터 치료',
        image: pr(16),
        type: 'product',
        detailImage: pr(16),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'xeomin',
        category: [],
        name: '제오민',
        engName: 'Xeomin',
        desc: ['자연스러운 주름 개선', '매끄러운 피부 표현'],
        point: '주름, 윤곽, 자연스러움',
        image: pr(17),
        type: 'product',
        detailImage: pr(17),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'hitox',
        category: [],
        name: '하이톡스',
        engName: 'Hitox',
        desc: ['잔주름 개선', '또렷한 얼굴 라인'],
        point: '주름, 탄력, 윤곽',
        image: pr(18),
        type: 'product',
        detailImage: pr(18),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'coretox',
        category: [],
        name: '코어톡스',
        engName: 'Coretox',
        desc: ['표정주름 개선', '자연스러운 얼굴 라인'],
        point: '주름, 윤곽, 자연스러움',
        image: pr(19),
        type: 'product',
        detailImage: pr(19),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'aha-bha',
        category: [],
        name: 'AHA/BHA',
        engName: 'AHA/BHA',
        desc: ['피부 타입별 맞춤형 각질 스케일링', '면포성 여드름 및 피지 분비 조절'],
        point: '각질, 피지, 여드름',
        image: pr(20),
        type: 'product',
        detailImage: pr(20),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'pdrn',
        category: [],
        name: 'PDRN',
        engName: 'PDRN',
        desc: ['연어 주사 성분으로 손상 세포 복구', '염증 완화 및 빠른 피부 진정 효과'],
        point: '재생, 진정, 상처 치료',
        image: pr(21),
        type: 'product',
        detailImage: pr(21),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'mounjaro',
        category: [],
        name: '마운자로',
        engName: 'Mounjaro',
        desc: ['체지방 감소 지원', '체중 관리 도움'],
        point: '체중 감량, 대사 활성화',
        image: pr(22),
        type: 'product',
        detailImage: pr(22),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'contour-inj',
        category: [],
        name: '윤곽주사',
        engName: 'Contour Injection',
        desc: ['얼굴 지방 분해, 매끄러운 라인 정리', '윤곽 정리, 얼굴 지방 감소'],
        point: '윤곽 정리, 얼굴 지방 감소',
        image: pr(23),
        type: 'product',
        detailImage: pr(23),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'signature-ha',
        category: [],
        name: '시그니처 HA',
        engName: 'Signature HA',
        desc: ['고수분 히알루론산 밀착 공급', '강력한 속건조 해결 및 물광 효과'],
        point: '보습, 물광, 속건조 케어',
        image: pr(24),
        type: 'product',
        detailImage: pr(24),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'peeling',
        category: [],
        name: '필링',
        engName: 'Peeling',
        desc: ['묵은 각질 세포 탈락 및 턴오버 촉진', '거친 피부 결 및 안색 정화 효과'],
        point: '피부결, 안색, 재생',
        image: pr(25),
        type: 'product',
        detailImage: pr(25),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
    {
        slug: 'scrubber',
        category: [],
        name: '스크러버',
        engName: 'Scrubber',
        desc: ['초은파 미세 진동을 이용한 각질 제거', '잔여 노폐물 청소 및 딥클렌징'],
        point: '각질, 피지, 노폐물',
        image: pr(26),
        type: 'product',
        detailImage: pr(26),
        subTitle: '',
        introDescription: '',
        principles: [],
    },
];

export const getSolutionBySlug = (slug: string): SolutionItem | undefined => {
    return solutions.find((item) => item.slug === slug);
};

// messages/solutions/{locale}.json 항목 하나의 모양 (desc/point는 항상, 나머지는 3개 항목만 존재)
type SolutionTranslation = Partial<
    Pick<SolutionItem, 'desc' | 'point' | 'subTitle' | 'introDescription' | 'principles'>
>;

// ko 이외 로케일에서 desc/point/subTitle/introDescription/principles 를 번역본으로 덮어씌운다.
// name/engName/image/slug 등 나머지 필드는 그대로 유지(브랜드명은 항상 engName으로 별도 분기).
export const localizeSolution = (item: SolutionItem, override?: SolutionTranslation): SolutionItem =>
    override ? { ...item, ...override } : item;

// 슬러그 배열 → 순서대로 아이템 반환 (시술 페이지 items 용)
export const getSolutionsBySlugs = (slugs: string[]): SolutionItem[] =>
    slugs.map((s) => getSolutionBySlug(s)).filter(Boolean) as SolutionItem[];

// 메인 SOLUTION 영역 탭
export const mainSolutionTabs = [
    { key: 'pigment', label: '색소', slugs: ['lipot', 'excelv', 'spectra', 'pico'] },
    { key: 'lifting', label: '리프팅', slugs: ['ulthera', 'onda', 'vro', 'juvelook-volume'] },
    { key: 'acne', label: '여드름', slugs: ['gold-ptt', 'potenza'] },
    { key: 'redness', label: '주사/홍조', slugs: ['excelv', 'gold-ptt', 'potenza'] },
];

export const getSolutionsByCategory = (categoryKey: string): SolutionItem[] => {
    const tab = mainSolutionTabs.find((t) => t.key === categoryKey);
    if (!tab) return [];
    return getSolutionsBySlugs(tab.slugs);
};
